theme: jekyll-theme-chirpy

title: Shaoless
author: Shaoless
email: zhangfeivariflight@gmail.com
# social links
github_username:  Jsamchow # DO NOT include the @ character, or else the build will fail!
show_excerpts: false # set to false to remove excerpts on the homepage
