theme: minima

title: shaoless
author: shaoless
email: zhangfeivariflight@gmail.com
# social links
github_username:  shaoless # DO NOT include the @ character, or else the build will fail!
show_excerpts: false # set to false to remove excerpts on the homepage
